### PR TITLE
Expand location data to use whatever data is available

### LINKED ISSUE #48: Package location often in different field of json response
**Describe the bug**
The package location is often returned in the field named "d" in the json response. Currently the field named "c" is used and is often (always?) empty.

**To Reproduce**
Observe missing 'location' data.

**Expected behavior**
Location should be assigned from the non-empty value that contains the location string.

**Screenshots**
n/a

**Additional context**
Replace [line 79 of profile.py](https://github.com/bachya/py17track/blob/5efff0e078d653441b2f1b13fa6d18830b1f2798/py17track/profile.py#L79) with:
`"location": event.get("c" if event.get("c") != '' else "d"),`

### PR DESCRIPTION
**Pull request by andreasbrett**
**Describe what the PR does:**
location data is in both: event.get("c") and event.get("d")

**Does this fix a specific issue?**
Fixes https://github.com/bachya/py17track/issues/48
  
**Checklist:**

- [x] Confirm that one or more new tests are written for the new functionality.
- [ ] Update `README.md` with any new documentation.
- [ ] Add yourself to `AUTHORS.md`.

### CODE REVIEW

**Comment by bachya** [comment]
Is this always true? Can you show an example of what would get output if (a) both fields exist/have values and (b) if one field is missing a value?

**Comment by andreasbrett** [comment]
No, it's not always true. I have 2 packages. One has field C filled, the other field D. Only using C (like currently implemented) leaves location empty for my second package. I have yet to see both fields filled.

Here's how the new implementation would render "location":

|field_C|field_D|location|
|---|---|---|
|test1|*empty*|test1|
|test1|*None*|test1|
|*empty*|test2|test2|
|*None*|test2|test2|
|test1|test2|test1 test2|
|*empty*|*empty*|*empty*|
|*None*|*None*|*empty*|

Note: *empty* is an empty String.

**Comment by bachya** [comment]
Thanks for the explanation, @andreasbrett. Seems reasonable to me. Please add a test and then we should be in good shape ot merge this.

**Comment by andreasbrett** [comment]
> Thanks for the explanation, @andreasbrett. Seems reasonable to me. Please add a test and then we should be in good shape ot merge this.

I added 3 test cases.

**Review by bachya — APPROVED** [review]
Looks good!

**Pull request merged**
