### PR TITLE
added attribute timestamp to package object

### PR DESCRIPTION
**Pull request by andreasbrett**
**Describe what the PR does:**
Add attribute "timestamp" for a package. I think it's helpful to know when the last status occurred.

**Does this fix a specific issue?**
No, it's a tiny feature enhancement
  
**Checklist:**

- [ ] Confirm that one or more new tests are written for the new functionality.
- [x] Update `README.md` with any new documentation.
- [ ] Add yourself to `AUTHORS.md`.

### CODE REVIEW

**Review by bachya — APPROVED** [review]
Thank you!

**Comment by andreasbrett** [comment]
> Thank you!

You're welcome. Really dig your HA addon but was wondering why it's still on py17track v2.0.2. Have there been any breaking changes that interfere with integration into HA?

**Comment by bachya** [comment]
@andreasbrett I've moved on from 17track, so I maintain this library, but don't do much with the HA integration. Available for anyone to pick up and run with!

**Comment by andreasbrett** [comment]
> @andreasbrett I've moved on from 17track, so I maintain this library, but don't do much with the HA integration. Available for anyone to pick up and run with!

Ah okay, got it.

**Comment by andreasbrett** [comment]
> Available for anyone to pick up and run with!

I'd like to bump this to the latest version on HA. Just checked and only breaking change can easily be implemented in HA addon. What are your release plans? I will raise a PR of the minor changes with the HA team once 3.0.2 is out.

**Comment by bachya** [comment]
@andreasbrett Just published 3.1.0, which includes this enhancement, to PyPI.

**Pull request merged**
